### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

### ISSUE THREAD

**Issue by sharif779** [tus/tus-py-client#73]
My `client.py`
```
from tusclient import client

# Set Authorization headers if it is required
# by the tus server.
my_client = client.TusClient('http://0.0.0.0:5000/resume_upload',
                              headers={'Authorization': 'Basic xxyyZZAAbbCC='})

# Set more headers.
#my_client.set_headers({'tag': 'value'})

# uploader = my_client.uploader('/home/sharif/Downloads/Customer_SpecialTerminationRates1_1_FRM_v20220930.xlsx', chunk_size=200)

# A file stream may also be passed in place of a file path.
fs = open('/home/sharif/Downloads/image.jpeg')
uploader = my_client.uploader(file_stream=fs, chunk_size=200, metadata={'filename':'aW5mby5tZXRh'})

# Upload a chunk i.e 200 bytes.
uploader.upload_chunk()

# Uploads the entire file.
# This uploads chunk by chunk.
uploader.upload()

# you could increase the chunk size to reduce the
# number of upload_chunk cycles.
uploader.chunk_size = 800
uploader.upload()

# Continue uploading chunks till total chunks uploaded reaches 1000 bytes.
uploader.upload(stop_at=1000)
```

```
Traceback (most recent call last):
  File "/media/sharif/Backup/test/Debug/TUS/client/client.py", line 18, in <module>
    uploader.upload_chunk()
  File "/media/sharif/Backup/test/Debug/TUS/venv/lib/python3.10/site-packages/tusclient/uploader/uploader.py", line 49, in upload_chunk
    self._do_request()
  File "/media/sharif/Backup/test/Debug/TUS/venv/lib/python3.10/site-packages/tusclient/uploader/uploader.py", line 72, in _do_request
    self.request.perform()
  File "/media/sharif/Backup/test/Debug/TUS/venv/lib/python3.10/site-packages/tusclient/request.py", line 77, in perform
    chunk = self.file.read(self._content_length)
  File "/usr/lib/python3.10/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
```

**Comment by Acconut** [comment]
I have never seen this error before but after reading https://stackoverflow.com/questions/42339876/error-unicodedecodeerror-utf-8-codec-cant-decode-byte-0xff-in-position-0-in, it might be related to the file not being opened in binary mode.

Can you try using this:

```python
fs = open('/home/sharif/Downloads/image.jpeg', mode='rb')
```

If this helps, we will also update the README.

**Comment by sharif779** [comment]
Thank You.Your solution worked.
I was tried following code.The error gone but some file md5sum did not match
`fs = open(log_location+file_name, encoding="ISO-8859-1")`

Now working perfectly by using following line
`fs = open(log_location+file_name, mode='rb')`

By the way now I am getting another error when enable resumable by 
```

storage_path = '{}/storage_file'.format("/etc/tus/storage_path")
# fs = open(log_location+file_name, encoding="ISO-8859-1")
fs = open(log_location+file_name, mode='rb')
uploader = my_client.uploader(file_stream=fs, chunk_size=chunk_size, metadata={'filename': file_name}, store_url=True,
                              url_storage=filestorage.FileStorage(storage_path), retries=2)
```
But returning following error
```
Traceback (most recent call last):
  File "TUS/client/client.py", line 43, in <module>
    uploader = my_client.uploader(file_stream=fs, chunk_size=chunk_size, metadata={'filename': file_name}, store_url=True,
  File "TUS/venv/lib/python3.10/site-packages/tusclient/client.py", line 53, in uploader
    return Uploader(*args, **kwargs)
  File "TUS/venv/lib/python3.10/site-packages/tusclient/uploader/baseuploader.py", line 128, in __init__
    self.__init_url_and_offset(url)
  File "TUS/venv/lib/python3.10/site-packages/tusclient/uploader/baseuploader.py", line 213, in __init_url_and_offset
    self.set_url(self.url_storage.get_item(key))
  File "TUS/venv/lib/python3.10/site-packages/tusclient/uploader/baseuploader.py", line 226, in set_url
    key = self._get_fingerprint()
  File "TUS/venv/lib/python3.10/site-packages/tusclient/uploader/baseuploader.py", line 219, in _get_fingerprint
    with self.get_file_stream() as stream:
  File "TUS/venv/lib/python3.10/site-packages/tusclient/uploader/baseuploader.py", line 241, in get_file_stream
    self.file_stream.seek(0)
ValueError: seek of closed file
```
