### ISSUE TITLE
upload_chunk() no longer works in 1.0.1

### ISSUE THREAD

**Issue by natefoo** [tus/tus-py-client#82]
This seems to be a bug introduced by 3bc58e5afa7cf5b87fcf349391936abdc63e6358 (#78), which relocates `set_url()` from `upload_chunk()` to `upload()`. Thus the following code:

```python
headers = {"x-api-key": "foo"}
path = "/foo"
chunk_size = 10**7
client = tusclient.client.TusClient("https://example.org", headers=headers)
uploader = client.uploader(
    file_path=path,
    chunk_size=chunk_size,
    metadata=None,
    store_url=False,
    url_storage=None,
)
file_size = uploader.get_file_size()
while uploader.offset < file_size:
    uploader.upload_chunk()
```

Results in the following (irrelevant upper stack components trimmed):
```pytb
Traceback (most recent call last):
  File "/home/nate/.virtualenvs/galaxy-upload2/lib/python3.10/site-packages/galaxy_upload/upload.py", line 105, in upload_file
    uploader.upload_chunk()
  File "/home/nate/.virtualenvs/galaxy-upload2/lib/python3.10/site-packages/tusclient/uploader/uploader.py", line 54, in upload_chunk
    self._do_request()
  File "/home/nate/.virtualenvs/galaxy-upload2/lib/python3.10/site-packages/tusclient/uploader/uploader.py", line 80, in _do_request
    self._retry_or_cry(error)
  File "/home/nate/.virtualenvs/galaxy-upload2/lib/python3.10/site-packages/tusclient/uploader/uploader.py", line 94, in _retry_or_cry
    raise error
  File "/home/nate/.virtualenvs/galaxy-upload2/lib/python3.10/site-packages/tusclient/uploader/uploader.py", line 77, in _do_request
    self.request.perform()
  File "/home/nate/.virtualenvs/galaxy-upload2/lib/python3.10/site-packages/tusclient/request.py", line 87, in perform
    raise TusUploadFailed(error)
tusclient.exceptions.TusUploadFailed: Invalid URL 'None': No scheme supplied. Perhaps you meant https://None?
```

I thought maybe we were using the uploader wrong (we specifically use the chunk method so we can show a progress bar) but this is essentially exactly how the example in the docs works.

**Comment by Acconut** [comment]
Thank you for reporting this! Would you be able to provide a patch for this?

**Comment by natefoo** [comment]
Thanks! Sorry I didn't get to fixing this myself.

**Comment by Acconut** [comment]
No worries, feel free to try out the new version and let me know if it still does not work :)
